import "./globals.css";
import { Inter } from 'next/font/google'
import Header from "@/components/Header";

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
})



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased bg-bgmint`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
